/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderTop: typeof import('./src/components/headerTop.vue')['default']
    IAntDesignHeartFilled: typeof import('~icons/ant-design/heart-filled')['default']
    IAntDesignHeartOutlined: typeof import('~icons/ant-design/heart-outlined')['default']
    IHugeiconsArrowLeft01: typeof import('~icons/hugeicons/arrow-left01')['default']
    IHugeiconsArrowRight01: typeof import('~icons/hugeicons/arrow-right01')['default']
    IHugeiconsArrowUp01: typeof import('~icons/hugeicons/arrow-up01')['default']
    IHugeiconsCheckmarkSquare01: typeof import('~icons/hugeicons/checkmark-square01')['default']
    IHugeiconsDragDrop: typeof import('~icons/hugeicons/drag-drop')['default']
    IHugeiconsExchange01: typeof import('~icons/hugeicons/exchange01')['default']
    IHugeiconsLinkSquare01: typeof import('~icons/hugeicons/link-square01')['default']
    IHugeiconsMessageLock01: typeof import('~icons/hugeicons/message-lock01')['default']
    IHugeiconsPause: typeof import('~icons/hugeicons/pause')['default']
    IHugeiconsPlay: typeof import('~icons/hugeicons/play')['default']
    IHugeiconsPlaylist03: typeof import('~icons/hugeicons/playlist03')['default']
    IHugeiconsRightToLeftListDash: typeof import('~icons/hugeicons/right-to-left-list-dash')['default']
    IHugeiconsSmartPhone01: typeof import('~icons/hugeicons/smart-phone01')['default']
    IHugeiconsSquareLock02: typeof import('~icons/hugeicons/square-lock02')['default']
    IHugeiconsSquareLockPassword: typeof import('~icons/hugeicons/square-lock-password')['default']
    IIcTwotoneCalendarToday: typeof import('~icons/ic/twotone-calendar-today')['default']
    ItemCard: typeof import('./src/components/itemCard.vue')['default']
    MarqueePlus: typeof import('./src/components/marqueePlus.vue')['default']
    MusicController: typeof import('./src/components/musicController.vue')['default']
    MusicList: typeof import('./src/components/musicList.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    Navigation: typeof import('./src/components/navigation.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    Playinglist: typeof import('./src/components/playinglist.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingItem: typeof import('./src/components/settingItem.vue')['default']
  }
}
